name: QA Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        run: uv python install 3.13

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v2

      - name: Verify Chrome Installation
        run: google-chrome --version

      - name: Install Dependencies
        run: uv sync

      - name: Run Tests
        env:
          HEADLESS: "True"
        run: uv run pytest -v